### PR TITLE
Fix OID4VCI auth code test script to use server-generated credential identifier

### LINKED ISSUE #884: OID4VCI auth code test script uses wrong credential identifier, causing UNKNOWN_CREDENTIAL_IDENTIFIER
### Describe the bug

When running the OID4VCI authorization code test flow via `keycloak-ssi` (`request_credential_with_auth_code_flow.sh`), the credential request fails with:

```
"error": "UNKNOWN_CREDENTIAL_IDENTIFIER",
"error_description": "No credential offer state for credential id: <CREDENTIAL
```

This happens because the script sends the **static credential configuration id** (e.g. `IdentityCredential`) as `credential_identifier` in the credential request.

### Version

26.5.0

### Expected behavior

The script should:
- Extract the `credential_identifier` from the token response (`authorization_details[0].credential_identifiers[0]`), and
- Use that value in the credential request body, so the credential endpoint finds the corresponding CredentialOfferState and issues the credential successfully.

### Actual behavior

_No response_

### How to Reproduce?

1. Deploy and Configure the OID4VCI environment with Keycloak 26.5.0.
2. Run keycloak-ssi test authcode IdentityCredential (or equivalent wrapper calling request_credential_with_auth_code_flow.sh).
3. Complete the browser login as the configured user.
4. Observe the credential endpoint response. 

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Awambeng**
Closes #884

### CODE REVIEW

File: oid4vci-deployment/src/credentials/request_credential_with_auth_code_flow.sh [hunk 1]
```diff
@@ -136,13 +136,24 @@ request_credential() {
...
   access_token=$(echo "$token_response" | jq -r '.access_token')
   if [ -z "$access_token" ] || [ "$access_token" == "null" ]; then
     error "Token exchange failed: $token_response"
     exit 1
   fi
+  
+  if [ -z "$credential_identifier" ] || [ "$credential_identifier" == "null" ]; then
+    error "Token response did not contain authorization_details.credential_identifiers: $token_response"
+    exit 1
+  fi
```
Comment (IngridPuppet) [inline oid4vci-deployment/src/credentials/request_credential_with_auth_code_flow.sh]: Taking the null check on "$credential_identifier" closer to the extraction of the variable will improve readability.

File: oid4vci-deployment/config.yaml [hunk 2]
```diff
@@ -14,7 +14,7 @@ keycloak:
   # Branch to use for custom Keycloak
   target_branch: "main"
   # Keycloak version
-  version: "999.0.0-SNAPSHOT"
+  version: "26.5.0"
   # Directory name for cloned Keycloak repo
```
Comment (IngridPuppet) [inline oid4vci-deployment/config.yaml]: I guess this update follows the recent recommendation of the SIG meeting. Do you confirm you ran a large-scale check of operations in the tool?

**Review by tnorimat — APPROVED** [review]

**Comment by tnorimat** [comment]
Thank you!
